version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f temp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rails_tutorial_docker
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

volumes:
  db-volume:
